name: drop_shadow_image
description: A new Flutter package for creating drop shadow of image with a lot of properties to make it look much good.
version: 0.9.1
homepage: https://github.com/saquibansari0101/drop_shadow_image

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

